apiVersion: v1
kind: Service
metadata:
  name: github-api-service
spec:
  type: NodePort
  selector:
    app: github-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
