version: '3'

vars:
  deployment_file: deployment.yaml
  service_file: service.yaml

tasks:
  deploy:
    desc: Apply Kubernetes deployment and service files to Minikube
    cmds:
      - minikube start
      - kubectl apply -f {{.deployment_file}}
      - kubectl apply -f {{.service_file}}

  status:
    desc: Check the status of pods and services
    cmds:
      - kubectl get pods
      - kubectl get svc

  all:
    desc: Run the full pipeline
    cmds:
      - task: deploy
      - task: status
